// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell execution capability for a model.
 */
export type ConfigShellToolType = "default" | "local" | "unified_exec" | "disabled" | "shell_command";
