// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInstructionsVariables = { personality_default: string | null, personality_friendly: string | null, personality_pragmatic: string | null, };
