// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyPatchToolType } from "./ApplyPatchToolType";
import type { ConfigShellToolType } from "./ConfigShellToolType";
import type { InputModality } from "./InputModality";
import type { ModelAvailabilityNux } from "./ModelAvailabilityNux";
import type { ModelInfoUpgrade } from "./ModelInfoUpgrade";
import type { ModelMessages } from "./ModelMessages";
import type { ModelVisibility } from "./ModelVisibility";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningEffortPreset } from "./ReasoningEffortPreset";
import type { ReasoningSummary } from "./ReasoningSummary";
import type { TruncationPolicyConfig } from "./TruncationPolicyConfig";
import type { Verbosity } from "./Verbosity";
import type { WebSearchToolType } from "./WebSearchToolType";

/**
 * User-configurable overrides for model metadata.
 */
export type ModelMetadataOverrides = { display_name: string | null, description: string | null, default_reasoning_level: ReasoningEffort | null, supported_reasoning_levels: Array<ReasoningEffortPreset> | null, shell_type: ConfigShellToolType | null, visibility: ModelVisibility | null, supported_in_api: boolean | null, priority: number | null, availability_nux: ModelAvailabilityNux | null, upgrade: ModelInfoUpgrade | null, base_instructions: string | null, model_messages: ModelMessages | null, supports_reasoning_summaries: boolean | null, default_reasoning_summary: ReasoningSummary | null, support_verbosity: boolean | null, default_verbosity: Verbosity | null, apply_patch_tool_type: ApplyPatchToolType | null, web_search_tool_type: WebSearchToolType | null, truncation_policy: TruncationPolicyConfig | null, supports_parallel_tool_calls: boolean | null, supports_image_detail_original: boolean | null, context_window: bigint | null, auto_compact_token_limit: bigint | null, effective_context_window_percent: bigint | null, experimental_supported_tools: Array<string> | null, input_modalities: Array<InputModality> | null, prefer_websockets: boolean | null, };
