// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInstructionsVariables } from "./ModelInstructionsVariables";

/**
 * A strongly-typed template for assembling model instructions and developer messages. If
 * instructions_* is populated and valid, it will override base_instructions.
 */
export type ModelMessages = { instructions_template: string | null, instructions_variables: ModelInstructionsVariables | null, };
