// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visibility of a model in the picker or APIs.
 */
export type ModelVisibility = "list" | "hide" | "none";
