// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";

/**
 * A reasoning effort option that can be surfaced for a model.
 */
export type ReasoningEffortPreset = { 
/**
 * Effort level that the model supports.
 */
effort: ReasoningEffort, 
/**
 * Short human description shown next to the effort in UIs.
 */
description: string, };
