// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-provided truncation policy metadata for a model.
 */
export type TruncationMode = "bytes" | "tokens";
